name: Release Upload
author: Trinovantes
description: Upload multiple assets to an existing GitHub release

inputs:
  release_id:
    description: The id for the release
    required: true
  upload_url:
    description: The upload URL for the release
    required: true
  files:
    description: Files to upload
    required: true

runs:
  using: composite
  steps:
    - uses: oven-sh/setup-bun@v2

    - run: |-
        cd "${{ github.action_path }}"
        bun install
        cd -
      shell: bash

    - run: bun run "${{ github.action_path }}/src/main.ts"
      shell: bash
      env:
        release_id: ${{ inputs.release_id }}
        upload_url: ${{ inputs.upload_url }}
        files: ${{ inputs.files }}
