name: Release Upload
author: Trinovantes
description: Upload multiple assets to an existing GitHub release

inputs:
  release_id:
    description: The id for the release
    required: true
  upload_url:
    description: The upload URL for the release
    required: true
  files:
    description: Files to upload
    required: true

runs:
  using: composite
  steps:
    - uses: pnpm/action-setup@v4
      with:
        version: 10
        run_install: false

    - uses: actions/setup-node@v4
      with:
        node-version: 22
        cache: pnpm

    - run: |-
        cd "${{ github.action_path }}"
        pnpm install --frozen-lockfile
        cd -
      shell: bash

    - run: node "${{ github.action_path }}/src/main.ts"
      shell: bash
      env:
        release_id: ${{ inputs.release_id }}
        upload_url: ${{ inputs.upload_url }}
        files: ${{ inputs.files }}
