name: Latest Tag

on:
  push:
    tags:
      - 'v*'

env:
  AUTO_TAG: latest
  AUTO_TITLE: Latest Build

jobs:
  latest_tag:
    name: Latest Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Current Release
        id: update_current
        uses: Trinovantes/action-automatic-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          is_prerelease: false

      - name: Update Latest Build Release
        uses: Trinovantes/action-automatic-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          auto_release_tag: ${{ env.AUTO_TAG }}
          auto_release_title: ${{ env.AUTO_TITLE }}
          is_prerelease: false
