name: Latest Tag

on:
  push:
    tags:
      - 'v*'

jobs:
  latest_tag:
    name: Latest Tag
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v2

      - name: Update Current Release
        id: update_current
        uses: Trinovantes/action-automatic-release@master
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          is_prerelease: false
